# **INTRODUCTION TO NUMPY**

In [1]:
import numpy as np

In [2]:
print("Hello, I will be the best ML engineer")

Hello, I will be the best ML engineer


In [3]:
myarr = np.array([1,2,3,4,5])

In [4]:
print(myarr)

[1 2 3 4 5]


Using numpy one can play with storage of each integer, you can store it in 8bit, 64bit and so on

In [5]:
myarr = np.array([1,2,3,4,5,2], np.int8)

In [6]:
myarr

array([1, 2, 3, 4, 5, 2], dtype=int8)

As 555 was too big for 8bit storage, we have to modify it by going for 32 or 64 bit

In [7]:
twoD_arr = np.array([[1,2,3],[4,5,6]], np.int8)

In [8]:
twoD_arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

numpy can also tell us about shape/structure of the array as well as about data type (8 bit, 32 bit so on)

In [9]:
twoD_arr.shape

(2, 3)

## **Array Creation**

#### 1. From python objects (List, tuples)

In [10]:
listarray = np.array([[1,2,3],[4,6,5],[23,6,3]])

In [11]:
listarray

array([[ 1,  2,  3],
       [ 4,  6,  5],
       [23,  6,  3]])

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
listarray[2,0] = 6

In [16]:
listarray

array([[1, 2, 3],
       [4, 6, 5],
       [6, 6, 3]])

#### 2. Intrinsic NumPy array creation functions

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(10,100,7)

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.diag([1,2,1,2])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 2]])

In [22]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

## **NUMPY AXIS**

In [31]:
num = [[1,2,3],[4,6,5],[8,7,1]]

In [32]:
arr = np.array(num)

In [33]:
arr

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 1]])

In [34]:
arr.sum(axis=0)

array([13, 15,  9])

In [35]:
arr.sum(axis=1)

array([ 6, 15, 16])

In [36]:
arr.T


array([[1, 4, 8],
       [2, 6, 7],
       [3, 5, 1]])

In [37]:
arr.flat


In [38]:
for item in arr.flat:
    print(item)

1
2
3
4
6
5
8
7
1


In [39]:
arr.ndim

2

In [40]:
arr.size

9

In [41]:
arr.nbytes

72

In [42]:
one = np.array([1,22,21,498,0])

In [43]:
one.argmax()

np.int64(3)

In [44]:
one.argmin()

np.int64(4)

In [45]:
one.argsort()

array([4, 0, 2, 1, 3])

In [46]:
arr.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [2, 1, 0]])

In [47]:
arr

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 1]])

In [48]:
arr.argmin()

np.int64(0)

In [49]:
arr.argmax()

np.int64(6)

In [50]:
arr.argmax(axis=0)

array([2, 2, 1])

In [51]:
arr.argmin(axis=1)

array([0, 0, 2])

In [52]:
arr.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]])

## **OPERATIONS**

In [53]:
arr

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 1]])

In [54]:
arr2 = np.array([[9, 2, 0],
                [7, 6, 4],
                [3, 1, 2]])

In [55]:
arr2

array([[9, 2, 0],
       [7, 6, 4],
       [3, 1, 2]])

In [56]:
arr+arr2

array([[10,  4,  3],
       [11, 12,  9],
       [11,  8,  3]])

In [57]:
arr*arr2

array([[ 9,  4,  0],
       [28, 36, 20],
       [24,  7,  2]])

In [58]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.44948974, 2.23606798],
       [2.82842712, 2.64575131, 1.        ]])

## **Misc**

In [59]:
arr

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 1]])

In [60]:
np.where(arr>5)

(array([1, 2, 2]), array([1, 0, 1]))

In [61]:
np.count_nonzero(arr)

9

In [62]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))